site_name: 'Vapor Red'
copyright: 'Copyright &copy; 2019 Qutheory, LLC'
site_url: 'https://docs.vapor.red/'
nav:
- 'Overview': 'index.md'
- 'Quick Start': 'quick-start.md'
- 'Providers':
  - 'Digital Ocean': 'providers/digital-ocean.md'
  - 'AWS': 'providers/aws.md'
- 'Application':
  - 'Setup domain': 'application/setup-domain.md'
- 'Security':
  - 'Account security': 'security/account-security.md'
  - 'Server security': 'security/server-security.md'
- 'Company': 'company.md'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - pymdownx.superfences
  - toc:
      permalink: true
theme:
  language: 'en'
  name: 'material'
  logo: 'images/logo.svg'
  palette:
    primary: 'white'
    accent: 'purple'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
repo_url: http://github.com/qutheory/red-docs
edit_uri: https://github.com/qutheory/red-docs/edit/master/docs/
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/@codevapor'
    - type: 'slack'
      link: 'http://vapor.team/'
    - type: 'github'
      link: 'https://github.com/vapor'
  font:
    text: 'Roboto Slab'
    code: 'Source Code Pro'
